name: Android CI

on:
  push:
    tags:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: 使用正式配置覆盖测试配置
      run: cp -rf release_config config
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build aab
      run: ./gradlew bundleRelease
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: |
          app/build/outputs/bundle/release/app-release.aab
    - name: Upload Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          app/build/outputs/bundle/release/app-release.aab

